// Date: 20.10.2016 10:37:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.mistborn.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOberHerr extends ModelBase
{
	
  //fields
    ModelRenderer bein1;
    ModelRenderer bein2;
    ModelRenderer korper;
    ModelRenderer kopf;
    ModelRenderer arm1;
    ModelRenderer arm2;
  
  public ModelOberHerr()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      bein1 = new ModelRenderer(this, 0, 0);
      bein1.addBox(0F, 0F, 0F, 2, 7, 2);
      bein1.setRotationPoint(1F, 17F, 0F);
      bein1.setTextureSize(256, 256);
      bein1.mirror = true;
      setRotation(bein1, 0F, 0F, 0F);
      bein2 = new ModelRenderer(this, 0, 0);
      bein2.addBox(-2F, 0F, 0F, 2, 7, 2);
      bein2.setRotationPoint(-2F, 17F, 0F);
      bein2.setTextureSize(256, 256);
      bein2.mirror = true;
      setRotation(bein2, 0F, 0F, 0F);
      korper = new ModelRenderer(this, -3, 0);
      korper.addBox(0F, 0F, 0F, 7, 9, 2);
      korper.setRotationPoint(-4F, 8F, 0F);
      korper.setTextureSize(256, 256);
      korper.mirror = true;
      setRotation(korper, 0F, 0F, 0F);
      kopf = new ModelRenderer(this, 0, 0);
      kopf.addBox(0F, 0F, 0F, 3, 3, 2);
      kopf.setRotationPoint(-2F, 5F, 0F);
      kopf.setTextureSize(256, 256);
      kopf.mirror = true;
      setRotation(kopf, 0F, 0F, 0F);
      arm1 = new ModelRenderer(this, 0, 0);
      arm1.addBox(0F, 0F, 0F, 2, 7, 2);
      arm1.setRotationPoint(3F, 8F, 0F);
      arm1.setTextureSize(256, 256);
      arm1.mirror = true;
      setRotation(arm1, 0F, 0F, 0F);
      arm2 = new ModelRenderer(this, 0, 0);
      arm2.addBox(-2F, 0F, 0F, 2, 7, 2);
      arm2.setRotationPoint(-4F, 8F, 0F);
      arm2.setTextureSize(256, 256);
      arm2.mirror = true;
      setRotation(arm2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    bein1.render(f5);
    bein2.render(f5);
    korper.render(f5);
    kopf.render(f5);
    arm1.render(f5);
    arm2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
